from pathlib import Path

p = Path('src/hermes_ultra/skill_lifecycle.py')
s = p.read_text()
s = s.replace('_COMMIT_RE = re.compile(r"^[0-9a-fA-F]{40}$")\n', '_COMMIT_RE = re.compile(r"^[0-9a-fA-F]{40}$")\n_SHA256_RE = re.compile(r"^[0-9a-fA-F]{64}$")\n', 1)
old = '''@dataclass(frozen=True)\nclass Provenance:\n    repository: str\n    commit_sha: str\n    license: str\n    discovered_from: str\n\n    def __post_init__(self) -> None:\n        if not self.repository.strip():\n            raise ValueError("repository is required")\n        if not _COMMIT_RE.fullmatch(self.commit_sha):\n            raise ValueError("commit_sha must be a full 40-character hexadecimal SHA")\n        if not self.license.strip():\n            raise ValueError("license is required")\n        if not self.discovered_from.strip():\n            raise ValueError("discovered_from is required")\n'''
new = '''@dataclass(frozen=True)\nclass Provenance:\n    repository: str\n    commit_sha: str\n    license: str\n    discovered_from: str\n    skill_path: str | None = None\n    artifact_sha256: str | None = None\n\n    def __post_init__(self) -> None:\n        if not self.repository.strip():\n            raise ValueError("repository is required")\n        if not _COMMIT_RE.fullmatch(self.commit_sha):\n            raise ValueError("commit_sha must be a full 40-character hexadecimal SHA")\n        if not self.license.strip():\n            raise ValueError("license is required")\n        if not self.discovered_from.strip():\n            raise ValueError("discovered_from is required")\n        bound = self.skill_path is not None or self.artifact_sha256 is not None\n        if bound and (self.skill_path is None or self.artifact_sha256 is None):\n            raise ValueError("skill_path and artifact_sha256 must be provided together")\n        if self.skill_path is not None:\n            parts = self.skill_path.split('/')\n            if (not self.skill_path or self.skill_path.startswith('/') or self.skill_path.endswith('/') or '\\\\' in self.skill_path or any(part in {'', '.', '..'} or ':' in part for part in parts)):\n                raise ValueError("skill_path must be a canonical relative POSIX path")\n            if not _SHA256_RE.fullmatch(self.artifact_sha256 or ''):\n                raise ValueError("artifact_sha256 must be a SHA-256 hex digest")\n            object.__setattr__(self, 'artifact_sha256', (self.artifact_sha256 or '').lower())\n'''
if old not in s:
    raise SystemExit('Provenance patch context missing')
s = s.replace(old, new, 1)
p.write_text(s)
